### ISSUE TITLE
对于非全屏的页面，点击位置和实际位置不同

### ISSUE THREAD

**Issue by zramals** [react-native-component/react-native-smart-gesture-password#4]
当前页面可能存在导航栏，或者布局不是全屏的，这样实际从 x: e.nativeEvent.pageX,y: e.nativeEvent.pageY的点会和显示的点有偏差，请问这个问题有什么好的解决方法嘛？

**Comment by cyqresig** [comment]
您好，目前布局需要全屏，手势范围的上部和下部都有预留自定义的View设置，您可以参考一下https://github.com/cyqresig/ReactNativeComponentDemos 中的示例
